#назва пейплайну
name: CI/CD Pipeline

#Тригери, коли запускати
on:
  push:
    branches: [main, develop] #при кожному пуш
  pull_request:
    branches: [main, develop] #при кожному пр

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      #завантажити код репозиторію
      - name: Checkout code
        uses: actions/checkout@v4

      #встановити node.js с 20 з кешуванням npm
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # встановити залежності з package-lock.json
      - name: Install dependencies
        run: npm ci

      # перевірка якості коду — якщо є помилки, pipeline зупиняється
      - name: Run linter
        run: npm run lint

      # запуск unit тестів з coverage
      - name: Run unit tests
        run: npm run test:coverage

      # продуктова збірка з Firebase-секретами
      - name: Build project
        run: npm run build
        env:
          VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}
          VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}
          VITE_FIREBASE_PROJECT_ID: ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
          VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}
          VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}
          VITE_FIREBASE_APP_ID: ${{ secrets.VITE_FIREBASE_APP_ID }}
          VITE_APP_STATUS: Production Mode
